### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by parksj10** [dc-js/react-dc-js#139]
I realize this is quite a long shot, but I'm wondering if we can use the typings from @types/dc to create typings for the functions in this library. I'm willing to help out, but I'm relatively new to creating type files and I'm having trouble with some of the code (I already started trying this on my end).

For example: 

```js
export function baseMixin(chart, props) {...
```

seems like it should become approximately

```js
export function baseMixin(chart: DCGraphicType, props: BaseMixin<any>) {...
```

where 

```js
export type DCGraphicType =
  | dc.PieChart
  | dc.SunburstChart
  | dc.BarChart
  | dc.LineChart
  | dc.DataCountWidget
  | dc.DataTableWidget
  | dc.DataGridWidget
  | dc.BubbleChart
  | dc.CompositeChart
  | dc.SeriesChart
  | dc.GeoChoroplethChart
  | dc.BubbleOverlayChart
  | dc.RowChart
  | dc.ScatterPlot
  | dc.NumberDisplayWidget
  | dc.HeatMap
  | dc.BoxPlot
  | dc.SelectMenu
  | dc.TextFilterWidget
  | dc.CBoxMenu;
```

however, it seems like `showControls, id` are not on the BaseMixin, amongst other hurdles. I'd be open to hearing how best to approach this issue, as I tried debugging the playground but it doesn't seem there are source maps...

**Comment by plourenco** [comment]
Hey @parksj10, thanks for contributing!

That seems like the right approach, nearly all of the typings should apply here, as the methods are the same.

There are corner cases, as you mentioned, such as `showControls` (among others being developed). This one is essentially a shorthand for `turnOnControls` and `turnOffControls`. As these actions are declarative in dc.js, I took the opportunity to convert them to a more idiomatic react approach based on a single value `showControls=true` (means turnOnControls), otherwise, I couldn't represent them correctly.
`id` refers to an identifier to keep track of the chart in an internal registry (I'm strongly considering to keep it as prop but refactor it out of `baseMixin`)

As for the source maps, the playground is indeed a bit messy in terms of source maps. I'll have a look over an alternative and come back to this.

**Comment by plourenco** [comment]
Added source maps in 4b024b7c51fd0331f0c2097458cbeecb8baa4945
